emarket/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual category category { get; set; }
        public virtual cart cart { get; set; }
    }
}

emarket/Controllers/cartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using emarket.Models;


namespace emarket.Controllers
{
    public class CartsController : Controller
    {
        private emarketEntities db = new emarketEntities();
        // GET: Carts
        public ActionResult Index()
        {
            var cart = db.carts;
            return View(cart.ToList());
        }
        public ActionResult AddToCart(int id)
        {
            var cart1 = new cart();
            DateTime localDate = DateTime.Now;
            cart1.added_at = localDate;
            cart1.product_Id = id;
            var cart2 = db.carts.Find(id);
            if (cart2 != null)
            {
                return RedirectToAction("Filter", "products");
            }
            else
            {
                db.carts.Add(cart1);
                db.SaveChanges();
                return RedirectToAction("Filter", "products");
            }
        }

        public ActionResult Remove(int id)
        {
            var cart = db.carts.Find(id);
            if (cart != null)
            {
                db.carts.Remove(cart);
            }
            db.SaveChanges();
            return RedirectToAction("Filter", "products");
        }
    }
}

emarket/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using emarket.Models;
using System.IO;
using emarket.ViewModels;

namespace emarket.Controllers
{
    public class productsController : Controller
    {
        private emarketEntities db = new emarketEntities();

        // GET: products
        public ActionResult Index()
        {
            var products = db.products.Include(p => p.category);
            return View(products.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.Category_Id = new SelectList(db.categories, "Id", "Category_Name");
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Description,Image,Category_Id")] product product, HttpPostedFileBase imgFile)
        {
            if (imgFile == null)
            {
                ViewBag.error = "Requred";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    String path = "";
                    if (imgFile.FileName.Length > 0)
                    {
                        path = "~/images/" + Path.GetFileName(imgFile.FileName);
                        imgFile.SaveAs(Server.MapPath(path));
                    }
                    product.Image = path;
                    db.products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Filter");
                }
            }
            ViewBag.Category_Id = new SelectList(db.categories, "Id", "Category_Name", product.Category_Id);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            TempData["imgpath"] = product.Image;
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category_Id = new SelectList(db.categories, "Id", "Category_Name", product.Category_Id);
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Description,Image,Category_Id")] product product, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {
                if (imgFile != null)
                {
                    String path = "";
                    if (imgFile.FileName.Length > 0)
                    {
                        path = "~/images/" + Path.GetFileName(imgFile.FileName);
                        imgFile.SaveAs(Server.MapPath(path));
                    }
                    product.Image = path;
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Filter");
                }
                else
                {
                    product.Image = TempData["imgpath"].ToString();
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Filter");
                }
            }
            ViewBag.Category_Id = new SelectList(db.categories, "Id", "Category_Name", product.Category_Id);
            return View(product);
        }
        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            cart Cart = db.carts.Find(id);
            if (Cart != null)
            {
                db.carts.Remove(Cart);
            }
            db.SaveChanges();
            return RedirectToAction("Filter");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //Search by product
        //public ActionResult Filter(string search)
        //{
        //    return View(db.products.Where(item => item.Name.Contains(search) || search == null).ToList());
        //}

        //Search by Category
        public ActionResult Filter(string search)
        {
            var products = db.products.Include(p => p.category).ToList();

            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(item => item.category.Category_Name.Contains(search) || search == null).ToList();
            }
            var cart = db.carts.ToList();
            var viewModel = new ProductCartsViewModel
            {
                carts = cart,
                products = products
            };
            return View(viewModel);
        }

    }
}

emarket/Views/products/Create.cshtml
@model emarket.Models.product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","products",FormMethod.Post,new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imgFile" name="imgFile" />
                @*@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                <div class="text-danger">@ViewBag.error</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Products", "Filter", null, new { @class = "btn breadcrumb" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

emarket/Views/products/Delete.cshtml
@model emarket.Models.product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Image)" width="70" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.Category_Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn breadcrumb" /> 
    @Html.ActionLink("Back to Products", "Filter", null, new { @class = "btn breadcrumb" })
</div>
    }
</div>

emarket/Views/products/Details.cshtml
@model emarket.Models.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd class="list-group-item text-center" style="background-color: #CCCCCC; font-size:23px;">
            @Html.DisplayFor(model => model.Name) - @Html.DisplayFor(model => model.Price) EGP ( @Html.DisplayFor(model => model.category.Category_Name))
        </dd>
        <dd class="text-center">
            <img src="@Url.Content(Model.Image)" width="300" height="350" />
        </dd>
        <dd class="text-center" style="font-size:17px;">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div class="btn-group btn-group-justified">
    <div class="btn-group">
        @Html.ActionLink("Update", "Edit", null, new { id = Model.Id }, new { @class = "btn btn-success" })
    </div>
    <div class="btn-group"></div>
    <div class="btn-group">
        @Html.ActionLink("Delete", "Delete", null, new { id = Model.Id }, new { @class = "btn btn-danger" })
    </div>
</div>
<br />
<div>
    @Html.ActionLink("Back to Products", "Filter", null, new { @class = "btn breadcrumb  " })
</div>

emarket/Views/products/Edit.cshtml
@model emarket.Models.product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(Html.BeginForm("Edit", "products", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.Image)" alt="..." width="242" height="200">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                <input type="file" id="imgFile" name="imgFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Products", "Filter", null, new { @class = "btn breadcrumb  " })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

emarket/Views/products/Filter.cshtml
@model emarket.ViewModels.ProductCartsViewModel
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    <div class="container" style="width:100%;margin-top:2%">
        @*<a href="href=" @Url.Action("Index", "carts", null) class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal" role="button">Show my cart</a>*@
        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h3 class="modal-title">Cart</h3>
                    </div>
                    <div class="modal-body">
                        <form id="myForm">
         <table class="table table-hover table-striped">
            <tbody class="table-bordered">
                @foreach (var item in Model.carts)
                {
                <tr>
                    <td>
                        <a href=" @Url.Action("Remove","Carts",new { id=item.product_Id } )" class="btn btn-danger">Remove</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.product.Name) - @Html.DisplayFor(modelItem => item.product.Price) EGP<br />

                        @{
                            TimeSpan ts = new TimeSpan();
                            ts = DateTime.Now - item.added_at.Value;

                            //seconds ago
                            if (ts.TotalMinutes < 1)
                            {

                                @Html.Label("just now")
                            }
                            //min ago
                            else if (ts.TotalHours < 1)
                            {
                                if ((int)ts.TotalMinutes == 1)
                                {
                                    @Html.Label("a Minute ago")
                                }
                                else
                                {
                                    @Html.Label((int)ts.TotalMinutes + " Minutes ago")
                                }

                            }
                            //hours ago
                            else if (ts.TotalDays < 1)
                            {
                                if ((int)ts.TotalHours == 1)
                                {
                                    @Html.Label("an Hour ago")
                                }
                                else
                                {
                                    @Html.Label((int)ts.TotalHours + " Hours ago")
                                }
                            }
                            //days ago
                            else if (ts.TotalDays < 7)
                            {
                                if ((int)ts.TotalDays == 1)
                                {
                                    @Html.Label("a Day ago")
                                }
                                else
                                {
                                    @Html.Label((int)ts.TotalHours + " Days ago")
                                }

                            }
                            //weeks ago
                            else if (ts.TotalDays < 30.4368)
                            {
                                if ((int)(ts.TotalDays / 7) == 1)
                                {
                                    @Html.Label("a Week ago")
                                }
                                else
                                {
                                    @Html.Label((int)(ts.TotalDays / 7) + " Weeks ago")
                                }
                            }
                            //months ago
                            else if (ts.TotalDays < 365.242)
                            {
                                if ((int)(ts.TotalDays / 30.4368) == 1)
                                {
                                    @Html.Label("a Month ago")
                                }
                                else
                                {
                                    @Html.Label((int)(ts.TotalDays / 30.4368) + " Months ago")
                                }
                            }

                            //years ago
                            else
                            {
                                if ((int)(ts.TotalDays / 365.242) == 1)
                                {
                                    @Html.Label("a Year ago")
                                }
                                else
                                {
                                    @Html.Label((int)(ts.TotalDays / 365.242) + " Years ago")
                                }
                            }
                        }
                    </td>

                </tr>
                }
            </tbody>
        </table>
                    </form>
                    <div style="text-align:center;display:none" id="loaderDiv">
                        <img src="~/Content/InternetSlowdown_Day.gif" width="150" /> @* //put any image in content folder*@
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="@Url.Action("Filter", "Products", null)" class="btn btn-default" data-dismiss="modal">Cancel</a>
                    @*<input type="reset" value="Submit" class="btn btn-success" id="btnSubmit" />*@
                </div>
                </div>
            </div>
        </div>
    </div>
}
<h2>Products</h2>
@using (Html.BeginForm())
{
    <br />
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">@@</span>
                @Html.TextBox("search", null, new { Type = "text", @class = "form-control" })
                <span class="input-group-btn">
                    @Html.ActionLink("Add New Product", "Create", null, new { @class = "btn btn-primary" })
                </span>

            </div>
        </div>
    </form>
    <br />
}

<table class="table">
    @foreach (var item in Model.products)
    {
        <div class=" col-lg-2 col-xs-6 col-sm-4 ">
            <div class="thumbnail">
                <a href="@Url.Action("Details","products",new { id=item.Id})">
                    <img src="@Url.Content(item.Image)" alt="..." width="270" height="210">
                </a>
                <div class="caption">
                    <h4>@item.Name</h4>
                    @*@Html.ActionLink(item.Name, "Details", null, new { id = item.Id }, new { @class = "btn btn-info btn-lg" })*@
                    <h4>@item.Price EGP</h4>
                    <a href="@Url.Action("AddToCart","Carts",new { id=item.Id} )" class="btn btn-primary fa fa-shopping-cart">Add To Cart</a>
                </div>
            </div>
        </div>
    }
</table>

<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {
            $("#loaderDiv").show();
            var myformdata = $("#myForm").serialize();
            $.ajax({
                type: "POST",
                url: "/Test/Index",
                data: myformdata,
                success: function () {
                    $("#loaderDiv").hide();
                    $("#myModal").modal("hide");
                }
            })
        })
    })
</script>